// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVABUuEIsfO_hCTXCAOXLksVNtxWPcnjs',
    appId: '1:719324778145:web:82017a168dc0beabaeeae0',
    messagingSenderId: '719324778145',
    projectId: 'nft-app-59bbc',
    authDomain: 'nft-app-59bbc.firebaseapp.com',
    storageBucket: 'nft-app-59bbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5gkp-vE1qgcVEA_MxAUumFg7wwuhSs-g',
    appId: '1:719324778145:android:747bb6d17a1dd756aeeae0',
    messagingSenderId: '719324778145',
    projectId: 'nft-app-59bbc',
    storageBucket: 'nft-app-59bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUjdXrjv2KoN7VnzmdE8bS9uUyLsDfvvM',
    appId: '1:719324778145:ios:8864fcee86d3f0ddaeeae0',
    messagingSenderId: '719324778145',
    projectId: 'nft-app-59bbc',
    storageBucket: 'nft-app-59bbc.appspot.com',
    iosBundleId: 'com.example.nftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUjdXrjv2KoN7VnzmdE8bS9uUyLsDfvvM',
    appId: '1:719324778145:ios:8864fcee86d3f0ddaeeae0',
    messagingSenderId: '719324778145',
    projectId: 'nft-app-59bbc',
    storageBucket: 'nft-app-59bbc.appspot.com',
    iosBundleId: 'com.example.nftApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVABUuEIsfO_hCTXCAOXLksVNtxWPcnjs',
    appId: '1:719324778145:web:540bed08f321e9d9aeeae0',
    messagingSenderId: '719324778145',
    projectId: 'nft-app-59bbc',
    authDomain: 'nft-app-59bbc.firebaseapp.com',
    storageBucket: 'nft-app-59bbc.appspot.com',
  );
}
